# Generated by Django 5.2.8 on 2025-12-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0002_remove_evento_imagem_alter_evento_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.CharField(default='outros', max_length=50),
        ),
        migrations.AddField(
            model_name='evento',
            name='imagem',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
